name: CI/CD Packer & Terraform

on:
  push:
    branches:
      - main  # Se ejecuta al hacer push en main

jobs:
  packer-build:
    name: Create AMI with Packer
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Packer
        uses: hashicorp/setup-packer@main

      - name: Iniciar Packer
        run: packer init .

      - name: Validar configuración de Packer
        run: packer validate packer.pkr.hcl

      - name: Construir imagen con Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: packer build packer.pkr.hcl

  terraform-deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: packer-build  # Se ejecuta después de que termine Packer
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
#        working-directory: ./terraform
        run: terraform init

      - name: Aplicar Terraform
#        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
